const fs = require('fs');
const path = require('path');

const TEMPLATE_PATH = path.join(__dirname, 'runs-data.template.js');

// Builds the full runs-data.js contents: real RUNS data followed by the
// unchanged utility functions (fmtPace, fmtDur, STATS, weeklyVolume, etc.)
// that runs.html's inline script relies on.
function renderDataFile(runs) {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
  const header =
    `// Generated by \`npm run sync\` (apps/runs/scripts/sync.js) from the Strava API.\n` +
    `// Do not edit by hand — see apps/runs/README.md to refresh.\n` +
    `// Last synced: ${new Date().toISOString()}\n`;
  const runsLiteral = `const RUNS = ${JSON.stringify(runs, null, 2)};\n\n`;
  return header + runsLiteral + template;
}

module.exports = { renderDataFile };
