apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: default
spec:
  ports:
  - nodePort: 30788
    port: 3000
    targetPort: 3000
  selector:
    app: portfolio
  type: LoadBalancer